#!/bin/zsh
##################################################
# Joshua's Backup Script
# Backups important files and configs to a tarball
##################################################

# Backup the list of programs installed
pacman -Qet > ~/installed_programs.txt

# List all files to be backed up

config=(~/.zshrc ~/.zlogin ~/.zshenv ~/.histfile ~/.Xresources ~/.xinitrc \
~/.gitconfig ~/.xbindkeysrc ~/.config/user-dirs.dirs ~/installed_programs.txt \
~/.Xmodmap)

dot_folders=(~/.mozilla ~/.vim ~/.ssh ~/.config/i3 ~/.config/i3status ~/utils)

backup_files=($config $dot_folders)

verbose="false"
if [[ "$verbose" == "true" ]];
	then flags="-chjvf"
else
	flags="-chjf"
fi

# Naming the file
day=$(date +%F)
comp="desktop"
backup_name="$comp-configs-$day.tar.bz2"

tar $flags ~/$backup_name $backup_files

rm ~/installed_programs.txt

