#!/bin/zsh
##################################################
# Joshua's Backup Script
# Backups my home folder. Does not back up my configs.
##################################################

# List all files to be backed up
backup_files=(~/Documents ~/Dropbox ~/Pictures ~/utils)

verbose="false"
if [[ "$verbose" == "true" ]];
	then flags="-chjvf"
else
	flags="-chjf"
fi

# Naming the file
day=$(date +%F)
comp="desktop"
backup_name="$comp-backup-$day.tar.bz2"

tar $flags ~/$backup_name $backup_files

